In [2]:
"""
金融歷史資料套件應用
finmind ：國內金融產品資料取得
# pip install FinMind 
"""

# 載入套件
from FinMind.data import DataLoader

api = DataLoader()

# 載入商品名稱，以台積電為例 2330
symbol = "2330"

# 取得歷史資料
# data = api.taiwan_stock_daily_adj(
data = api.taiwan_stock_daily(
    stock_id=symbol, 
    start_date="2023-01-01", 
    end_date="2024-3-31"
)

data

2024-04-05 11:05:38.333 | INFO     | FinMind.data.finmind_api:get_data:123 - download TaiwanStockPrice, data_id: 2330

,date,stock_id,Trading_Volume,Trading_money,open,max,min,close,spread,Trading_turnover
0,2023-01-03,2330,15311364,6871973708,446.0,453.5,443.0,453.0,4.5,22581
1,2023-01-04,2330,20626874,9310050329,449.5,455.0,448.5,449.5,-3.5,18233
2,2023-01-05,2330,23972099,10972616269,459.0,459.5,455.0,458.5,9.0,20752
3,2023-01-06,2330,21313593,9745142549,455.0,459.5,455.0,458.5,0.0,16635
4,2023-01-09,2330,49186355,23352375299,468.0,481.0,467.5,481.0,22.5,57305
...,...,...,...,...,...,...,...,...,...,...
290,2024-03-25,2330,21223414,16612693369,783.0,788.0,779.0,780.0,-5.0,24794
291,2024-03-26,2330,43103294,33847261033,788.0,792.0,776.0,782.0,2.0,35046
292,2024-03-27,2330,19732209,15418346943,785.0,785.0,779.0,779.0,-3.0,21006
293,2024-03-28,2330,28393398,21889883699,774.0,776.0,768.0,769.0,-10.0,39848
294,2024-03-29,2330,20212820,15682908766,769.0,781.0,768.0,779.0,10.0,18110